"""Initial

Revision ID: 1af0c7615454
Revises: 
Create Date: 2024-07-08 12:38:09.404536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af0c7615454'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('articles',
    sa.Column('name', sa.String(length=1023), nullable=False),
    sa.Column('term', sa.Enum('digital_transformation', 'transfer_of_digital_technology', 'digital_technology', 'end_to_end_digital_technology', 'breakthrough_technology', 'near_future_technology', 'gradually_introduced_technology', name='termrutypeenum'), nullable=False),
    sa.Column('terminology', sa.String(length=1023), nullable=False),
    sa.Column('author', sa.String(length=1023), nullable=False),
    sa.Column('key_words', sa.String(length=1023), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('usage_context', sa.String(length=1023), nullable=False),
    sa.Column('math_apparatus', sa.String(length=1023), nullable=False),
    sa.Column('solving', sa.String(length=1023), nullable=False),
    sa.Column('interests', sa.String(length=1023), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'en', name='langenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='_identifier_uc'),
    sa.UniqueConstraint('name', name='_name_uc')
    )
    op.create_table('problems',
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_solved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    op.drop_table('articles')
    op.drop_table('users')
    # ### end Alembic commands ###
