version: "3.8"
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: repo
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  api:
    build: 
      context: ../api/
      dockerfile: ../docker/api/dockerfile
    container_name: fastapi_container
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build: 
      context: ../web/
      dockerfile: ../docker/web/dockerfile
    container_name: react_container
    ports:
      - "80:80"
    depends_on:
      - db
