/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotAuthenticatedImport } from './routes/_notAuthenticated'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as NotAuthenticatedSignupImport } from './routes/_notAuthenticated/signup'
import { Route as NotAuthenticatedLoginImport } from './routes/_notAuthenticated/login'
import { Route as AuthenticatedLogoutImport } from './routes/_authenticated/logout'
import { Route as AuthenticatedArticleArticleIdImport } from './routes/_authenticated/article/$articleId'

// Create Virtual Routes

const AuthenticatedMyLazyImport = createFileRoute('/_authenticated/my')()
const AuthenticatedArticleIndexLazyImport = createFileRoute(
  '/_authenticated/article/',
)()

// Create/Update Routes

const NotAuthenticatedRoute = NotAuthenticatedImport.update({
  id: '/_notAuthenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedMyLazyRoute = AuthenticatedMyLazyImport.update({
  path: '/my',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/my.lazy').then((d) => d.Route),
)

const NotAuthenticatedSignupRoute = NotAuthenticatedSignupImport.update({
  path: '/signup',
  getParentRoute: () => NotAuthenticatedRoute,
} as any)

const NotAuthenticatedLoginRoute = NotAuthenticatedLoginImport.update({
  path: '/login',
  getParentRoute: () => NotAuthenticatedRoute,
} as any)

const AuthenticatedLogoutRoute = AuthenticatedLogoutImport.update({
  path: '/logout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedArticleIndexLazyRoute =
  AuthenticatedArticleIndexLazyImport.update({
    path: '/article/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/article/index.lazy').then((d) => d.Route),
  )

const AuthenticatedArticleArticleIdRoute =
  AuthenticatedArticleArticleIdImport.update({
    path: '/article/$articleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_notAuthenticated': {
      preLoaderRoute: typeof NotAuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/logout': {
      preLoaderRoute: typeof AuthenticatedLogoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_notAuthenticated/login': {
      preLoaderRoute: typeof NotAuthenticatedLoginImport
      parentRoute: typeof NotAuthenticatedImport
    }
    '/_notAuthenticated/signup': {
      preLoaderRoute: typeof NotAuthenticatedSignupImport
      parentRoute: typeof NotAuthenticatedImport
    }
    '/_authenticated/my': {
      preLoaderRoute: typeof AuthenticatedMyLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/article/$articleId': {
      preLoaderRoute: typeof AuthenticatedArticleArticleIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/article/': {
      preLoaderRoute: typeof AuthenticatedArticleIndexLazyImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthenticatedRoute.addChildren([
    AuthenticatedLogoutRoute,
    AuthenticatedMyLazyRoute,
    AuthenticatedArticleArticleIdRoute,
    AuthenticatedArticleIndexLazyRoute,
  ]),
  NotAuthenticatedRoute.addChildren([
    NotAuthenticatedLoginRoute,
    NotAuthenticatedSignupRoute,
  ]),
])

/* prettier-ignore-end */
